/**
 * Lista de palavras do gerador de senhas memorizaveis.
 *
 * Requisitos, verificados por teste em wordlist.test.ts:
 * - todas as entradas sao unicas;
 * - apenas [a-z], sem acentos, 3 a 12 letras;
 * - tamanho minimo garantido por WORDLIST_MIN_SIZE.
 *
 * O tamanho da lista alimenta o calculo de entropia em password.ts. Reduzir esta
 * lista reduz a entropia por palavra e faz os testes de politica falharem.
 */

/** Piso de tamanho da lista. Nao reduzir sem revisar PASSWORD_POLICY. */
export const WORDLIST_MIN_SIZE = 1024;

export const WORDS: readonly string[] = Object.freeze([
  "abacaxi", "abajur", "abelha", "aberto", "abobora", "abrigar", "abril", "abrir", "acampar", "achar", "aco",
  "acorde", "acordeao", "acougue", "acucar", "agenda", "agitado", "agosto", "agua", "aguia", "agulha", "ajudar",
  "alarme", "album", "alecrim", "alegre", "alerta", "alface", "alga", "algodao", "alho", "alicate", "alma",
  "almoxarifado", "alto", "aluminio", "aluno", "amarelo", "amargo", "ambar", "ameixa", "amendoim", "amizade",
  "amor", "amplificador", "ampulheta", "anao", "ancora", "andar", "andorinha", "anel", "angulo", "ano",
  "ansioso", "antigo", "apagado", "apontador", "aprender", "aranha", "arar", "arara", "arco", "argila",
  "armadura", "armario", "arquivo", "arroz", "arteria", "arvore", "aspero", "assar", "atalho", "atento",
  "atomo", "audio", "aula", "aurora", "aveia", "avenida", "aventura", "aviao", "aviso", "azedo", "azul",
  "bacia", "bairro", "baixar", "baixo", "balao", "balde", "baleia", "balsa", "bambu", "banana", "banco",
  "bandeira", "bandeja", "banheiro", "bar", "baralho", "barba", "barbante", "barco", "barro", "barulhento",
  "batata", "bateria", "bau", "beco", "bege", "beija", "beleza", "bengala", "besouro", "beterraba", "biblioteca",
  "bicho", "bicicleta", "bigode", "bilhete", "binoculo", "bispo", "blusa", "boca", "bochecha", "boi", "bola",
  "bolo", "bolsa", "bondade", "bonde", "bone", "bongo", "borboleta", "borda", "borracha", "bosque", "bota",
  "botao", "braco", "branco", "brasao", "bravo", "brilhante", "brincadeira", "brinco", "brisa", "broca",
  "bronze", "bruxa", "bule", "burro", "buscar", "bussola", "cabeca", "cabelo", "cabo", "cabra", "cachecol",
  "cachoeira", "cadeira", "caderno", "cafe", "caiaque", "caixa", "caju", "calca", "caldeirao", "calendario",
  "calma", "calmo", "cama", "camaleao", "camarao", "camelo", "camera", "caminhada", "caminhao", "caminho",
  "camisa", "campo", "canario", "cancao", "canela", "caneta", "canoa", "cantar", "cantil", "canto", "cao",
  "capa", "capacete", "capo", "caracol", "caranguejo", "cargo", "carne", "carrapato", "carregador", "carro",
  "carta", "cartao", "carteira", "carvao", "casa", "casaco", "casca", "castanha", "castelo", "castor", "cavaleiro",
  "cavalo", "cavar", "caverna", "cebola", "cegonha", "celula", "celular", "cem", "cenoura", "centeio", "centro",
  "ceramica", "cerca", "cerebro", "cereja", "cesta", "cevada", "chapeu", "charada", "chave", "chegar", "cheio",
  "cheirar", "chinelo", "chumbo", "churrascaria", "chuteira", "chuva", "chuveiro", "cidade", "cifra", "cigarra",
  "cilindro", "cilio", "cima", "cimento", "cinco", "cinema", "cinto", "cintura", "cinza", "circo", "circulo",
  "cisne", "clarinete", "claro", "clima", "clinica", "closet", "cobertor", "cobra", "cobre", "cobrir", "coco",
  "codigo", "codorna", "coelho", "coentro", "cofre", "cola", "colar", "colchao", "colher", "cometa", "compasso",
  "comprar", "computador", "concha", "conduzir", "cone", "consertar", "construir", "consulta", "contar",
  "continente", "conto", "contrato", "copo", "coracao", "coragem", "corajoso", "coral", "corda", "corpo",
  "corredor", "correio", "correr", "corrida", "cortar", "cortina", "coruja", "corvo", "costas", "costurar",
  "cotovelo", "couro", "couve", "cozinha", "cozinhar", "cravo", "creme", "crepusculo", "cristal", "cronometro",
  "cubo", "cuidar", "curativo", "curioso", "curto", "curva", "dado", "dama", "danca", "data", "decada",
  "dedal", "dedo", "defender", "densidade", "dente", "dentro", "deposito", "desafio", "descer", "desenhar",
  "deserto", "despensa", "despertador", "destino", "dez", "dezembro", "dia", "diamante", "diametro", "diploma",
  "disco", "distraido", "distrito", "dizer", "dobrar", "dobro", "doce", "dois", "domingo", "domino", "dourado",
  "dragao", "duende", "duna", "duro", "eclipse", "elefante", "elmo", "empilhadeira", "emprestar", "empurrar",
  "energia", "enigma", "ensaio", "ensinar", "entrar", "envelope", "equacao", "equipe", "escada", "escalar",
  "escola", "escorpiao", "escova", "escrever", "escritorio", "escudo", "escuro", "escutar", "esfera", "esmeralda",
  "espada", "espelho", "esperanca", "esperto", "espinafre", "espiral", "espirito", "esponja", "esquadro",
  "esquecer", "esquiar", "esquilo", "estacao", "estadio", "estado", "estanho", "estante", "estojo", "estomago",
  "estoque", "estrada", "estreito", "estrela", "estudar", "exame", "expedicao", "fabrica", "fabula", "faca",
  "fada", "falar", "falcao", "farinha", "farmacia", "farol", "fatura", "fechado", "fechar", "feijao", "feira",
  "feriado", "ferias", "ferro", "festa", "fevereiro", "figado", "figo", "filme", "fino", "fio", "firme",
  "fita", "flamingo", "flauta", "flecha", "flor", "floresta", "foca", "foco", "fogo", "fogueira", "foguete",
  "folha", "fone", "fonte", "fora", "forca", "forma", "formiga", "forte", "fosco", "foto", "fracao", "frango",
  "freio", "frente", "fresco", "frigideira", "frio", "fritar", "fronteira", "frouxo", "fruta", "funil",
  "furadeira", "gaita", "gaivota", "galaxia", "galho", "galpao", "gancho", "ganso", "garagem", "garca",
  "garfo", "garrafa", "gato", "gaveta", "gaviao", "gaze", "gelado", "gelo", "generoso", "gengibre", "gentil",
  "gigante", "ginasio", "girafa", "girar", "girassol", "giz", "goiaba", "gol", "golfinho", "gorila", "grafico",
  "gravata", "grilo", "grosso", "gruta", "guarda", "guardar", "guiar", "guindaste", "guitarra", "harmonia",
  "harpa", "helicoptero", "hexagono", "historia", "honesto", "hora", "hospital", "hotel", "humilde", "ideia",
  "ilha", "impar", "impressora", "inteiro", "intenso", "interruptor", "inverno", "iogurte", "jacare", "janeiro",
  "janela", "jaqueta", "jardim", "jarra", "jasmim", "joelho", "jogo", "jornada", "jovem", "julho", "junho",
  "juntar", "justica", "justo", "lado", "lagarto", "lago", "lagoa", "lagosta", "lampada", "lanca", "lanchonete",
  "lanterna", "lapis", "lar", "laranja", "largo", "latao", "lavar", "leal", "leao", "leite", "lembrar",
  "leme", "lenco", "lencol", "lenda", "lente", "lento", "ler", "lesma", "leste", "levantar", "leve", "lhama",
  "libelula", "liberdade", "limao", "limpar", "limpo", "lingua", "linha", "linho", "lirio", "liso", "livraria",
  "livro", "lixa", "lobo", "loja", "lombada", "longe", "longo", "lontra", "losango", "louva", "lua", "lula",
  "luminaria", "lupa", "luva", "luz", "maca", "macaco", "macio", "madeira", "madrugada", "maduro", "mago",
  "maio", "mala", "manga", "manha", "manjericao", "manso", "manteiga", "mao", "mapa", "maraca", "maratona",
  "marcador", "marco", "mare", "marfim", "margarida", "mariposa", "marrom", "martelo", "massa", "mastro",
  "mata", "media", "meia", "meio", "mel", "melancia", "melodia", "memoria", "mente", "mercado", "mergulhar",
  "mes", "mesa", "meta", "metade", "meteoro", "metro", "mexilhao", "microfone", "microscopio", "mil", "milhao",
  "milho", "minhoca", "minuto", "mito", "mochila", "modem", "moer", "molecula", "molhado", "monitor", "montar",
  "morango", "morcego", "morno", "morro", "morsa", "mosca", "mosquito", "moto", "motor", "mouse", "mula",
  "muro", "musculo", "museu", "musica", "nadar", "nariz", "navio", "nebulosa", "necessaire", "nervo", "neve",
  "niquel", "nivel", "noite", "norte", "nota", "nove", "novembro", "novo", "noz", "numero", "nuvem", "nylon",
  "oculos", "oeste", "oficina", "oito", "olhar", "olho", "ombro", "onca", "onda", "onibus", "orbita", "orelha",
  "orgao", "orquidea", "osso", "ostra", "ouro", "outono", "outubro", "ouvir", "ovelha", "ovo", "paciente",
  "padaria", "pagar", "pagina", "pais", "palco", "palha", "palma", "panda", "pandeiro", "panela", "pao",
  "papagaio", "papel", "papelao", "par", "parabrisa", "parafuso", "pardal", "parede", "parque", "partido",
  "partir", "passar", "passeio", "pasta", "patinar", "patinete", "pato", "pausa", "paz", "peao", "peca",
  "pedal", "pedra", "peito", "peixe", "pele", "pelicano", "peneira", "peneirar", "pensar", "pentagono",
  "pente", "pepino", "pera", "perder", "perereca", "perna", "perola", "perto", "peru", "pesado", "pescar",
  "pescoco", "pessego", "pia", "piano", "picante", "pilha", "pimenta", "pincel", "pinguim", "pintar", "piramide",
  "piscina", "pista", "pizzaria", "placa", "planador", "planeta", "plano", "plantar", "plastico", "plateia",
  "platina", "pneu", "poco", "podar", "poema", "poltrona", "polvo", "pomba", "ponte", "ponteiro", "ponto",
  "porao", "porcelana", "porco", "porta", "portao", "portaria", "porto", "potencia", "praca", "praia", "prata",
  "prateado", "prateleira", "prato", "prazo", "prego", "preto", "primavera", "primeiro", "princesa", "principe",
  "produto", "professor", "projeto", "proteger", "prova", "provar", "pular", "pulga", "pulmao", "pulseira",
  "pulso", "punho", "puxar", "quadra", "quadrado", "quadril", "quadro", "quarta", "quarto", "quatro", "quebrar",
  "queijo", "queixo", "quente", "quieto", "quinta", "quintal", "rabanete", "radio", "rainha", "raio", "raiz",
  "ralo", "rapido", "raposa", "raquete", "rato", "receber", "receita", "recepcao", "recibo", "rede", "regar",
  "regiao", "registro", "regua", "rei", "relogio", "remar", "remedio", "remo", "respeito", "restaurante",
  "resto", "retangulo", "reto", "retrovisor", "reuniao", "riacho", "rim", "rima", "rio", "ritmo", "roda",
  "rodovia", "rolo", "rosa", "rosto", "rota", "roteador", "roxo", "rua", "rubi", "sabado", "sabao", "sabedoria",
  "sabia", "sabio", "sacada", "saco", "safira", "saia", "sair", "sal", "sala", "salamandra", "salario",
  "salgado", "salsa", "saltar", "salvar", "sandalia", "sangue", "sapato", "sapo", "satelite", "saxofone",
  "scanner", "secar", "seco", "seculo", "seda", "segredo", "seguir", "segunda", "segundo", "seguro", "seis",
  "selo", "selva", "semana", "semear", "semente", "senha", "sentir", "separar", "sereia", "seringa", "serra",
  "servidor", "sete", "setembro", "sexta", "shampoo", "simples", "sinal", "sino", "sistema", "skate", "sobrancelha",
  "sofa", "sol", "soma", "sombrinha", "sonho", "sorveteria", "sotao", "suave", "subir", "sujo", "sul", "surfar",
  "tabela", "tablet", "tabua", "tabuleiro", "taca", "tacada", "taco", "tambor", "tanque", "tapete", "tarde",
  "tarefa", "tartaruga", "teatro", "tecido", "teclado", "telefone", "telescopio", "telhado", "temperatura",
  "tempo", "tenda", "tenis", "terca", "terceiro", "termometro", "terra", "terraco", "tesoura", "tesouro",
  "testa", "teto", "tigela", "tigre", "timido", "tinta", "titanio", "toalha", "tocar", "tomada", "tomate",
  "torneira", "tornozelo", "torre", "torta", "torto", "toupeira", "trabalho", "trapezio", "tras", "trator",
  "travessa", "travesseiro", "trem", "trena", "tres", "triangulo", "trigo", "trilha", "triplo", "triste",
  "trocar", "trombone", "trompete", "tronco", "trovao", "tuba", "tubarao", "tucano", "tulipa", "turma",
  "turquesa", "ultimo", "umido", "unha", "urso", "uva", "vacina", "vale", "varanda", "vazio", "veia", "vela",
  "velcro", "velejar", "velho", "veloz", "vender", "vento", "ver", "verao", "verdade", "verde", "vermelho",
  "verniz", "verso", "vespa", "vestido", "viagem", "video", "vidro", "vigiar", "vila", "viola", "violao",
  "violeta", "violino", "violoncelo", "vivo", "volante", "voltar", "volume", "xadrez", "xicara", "zebra",
  "zero", "zinco", "ziper",
]);
